'use client';
import {useEffect,useState,useRef} from 'react';
import {Heart,Plus,ArrowLeft,ArrowRight,Check,RotateCcw,Pencil,ShieldCheck,RefreshCw,Download,Camera,Wallet,CalendarDays,TrendingUp,Sparkles,Pause,Play,Archive,LockKeyhole} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {type State,type Snapshot,type Account,money,inputMoney,parseMoney,addMonth,monthName,todayBR,totals,rowsFor,dueDate,keyFor,scheduled} from '@/lib/model';
const labels={fixed:'Fixa',installment:'Parcela',optional:'Se usar',debt:'A negociar'};
const quotes=[['Em qualquer universo, o meu lugar favorito seria ao seu lado.','Doutor Estranho & Christine'],['Se o tempo nos desse mais uma dança, eu nunca soltaria a sua mão.','Steve Rogers & Peggy Carter'],['Mesmo quando o mundo muda, eu continuo escolhendo a nossa história.','Wanda & Visão'],['Entre todos os caminhos da cidade, o mais bonito é o que me leva até você.','Peter Parker & MJ'],['Escolheria construir todos os meus amanhãs com você.','Tony Stark & Pepper Potts']];
function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
function CurrencyInput({name,value,label}:{name:string;value:number;label:string}){return <label>{label}<div className="money-field"><span>R$</span><input name={name} aria-label={label} inputMode="decimal" required defaultValue={inputMoney(value)} placeholder="0,00"/></div></label>}
export default function Dashboard({viewer}:{viewer:string}){
 const [snap,setSnap]=useState<Snapshot|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[month,setMonth]=useState(todayBR().slice(0,7)),[person,setPerson]=useState('Todos'),[filter,setFilter]=useState('pending'),[tab,setTab]=useState('month'),[edit,setEdit]=useState<Account|null>(null),[settings,setSettings]=useState(false),[goalOpen,setGoalOpen]=useState(false),[photo,setPhoto]=useState(''),[photoAvailable,setPhotoAvailable]=useState(false),[quote,setQuote]=useState(0),[paused,setPaused]=useState(false),[archive,setArchive]=useState<Account|null>(null),[restore,setRestore]=useState<State|null>(null),[conflict,setConflict]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null),restRef=useRef<HTMLInputElement>(null),saving=useRef(false),editing=useRef(false),snapRef=useRef<Snapshot|null>(null);
 editing.current=!!edit||settings||goalOpen||!!restore;snapRef.current=snap;
 async function load(silent=false){try{const r=await fetch('/api/state',{cache:'no-store'});const body=await r.json() as Snapshot & {error:string};if(!r.ok)throw Error(body.error);setSnap(body);if(!silent){setError('');setConflict(false)}}catch(e){if(!silent)setError((e as Error).message)}}
 useEffect(()=>{void load();setPhoto('/api/photo?t='+Date.now());setPhotoAvailable(true);setPaused(matchMedia('(prefers-reduced-motion: reduce)').matches);const timer=setInterval(()=>{if(!saving.current&&!editing.current&&!document.hidden)void load(true)},20000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(paused)return;const t=setInterval(()=>{if(!document.hidden)setQuote(v=>(v+1)%quotes.length)},8000);return()=>clearInterval(t)},[paused]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();void Promise.resolve(context.registerTool({name:'read_monthly_budget',description:'Read the saved household budget for a month, in Brazilian reais.',inputSchema:{type:'object',properties:{month:{type:'string',pattern:'^20[0-9]{2}-(0[1-9]|1[0-2])$'}},required:['month'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const m=(input as {month:string}).month;if(!/^20\d\d-(0[1-9]|1[0-2])$/.test(m))throw Error('Mês inválido');if(!snapRef.current)throw Error('Dados indisponíveis');setMonth(m);const t=totals(snapRef.current.data,m);return {month:m,planned:money(t.planned),paid:money(t.paid),pending:money(t.pending),balance:money(t.balance)}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
 async function save(data:State,message:string){if(!snap||saving.current)return false;saving.current=true;setBusy(true);setError('');try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data,version:snap.version})});const body=await r.json() as Snapshot & {error:string};if(!r.ok){if(r.status===409)setConflict(true);throw Error(body.error)}setSnap(body);setNotice(message);setConflict(false);return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false);saving.current=false}}
 function mutate(fn:(s:State)=>void,message:string){if(!snap)return;const next=structuredClone(snap.data);fn(next);return save(next,message)}
 function pay(a:Account,m:string,undo=false){void mutate(s=>{const key=keyFor(a,m);if(undo)delete s.payments[key];else s.payments[key]={at:new Date().toISOString(),by:viewer,cents:a.cents}},undo?'Pagamento desfeito. A conta voltou às pendências.':'Conta concluída! O total a pagar foi atualizado.')}
 async function uploadPhoto(f:File){setBusy(true);try{const form=new FormData();form.append('photo',f);const r=await fetch('/api/photo',{method:'POST',body:form});const j=await r.json() as {error:string};if(!r.ok)throw Error(j.error);setPhoto('/api/photo?t='+Date.now());setPhotoAvailable(true);setNotice('Nossa foto foi atualizada.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function download(){if(!snap)return;const url=URL.createObjectURL(new Blob([JSON.stringify(snap.data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='nosso-universo-'+todayBR()+'.json';a.click();URL.revokeObjectURL(url)}
 const state=snap?.data;
 const all=state?totals(state,month):null;
 const t=state?totals(state,month,person):null;
 const pending=t?.rows.filter(r=>!r.payment)||[],paid=t?.rows.filter(r=>r.payment)||[];
 const shown=(filter==='pending'?pending:paid).sort((a,b)=>(a.due||month+'-99').localeCompare(b.due||month+'-99'));
 const future=state?Array.from({length:12},(_,i)=>({month:addMonth(month,i),...totals(state,addMonth(month,i),person)})):[];
 const totalDebt=state?.accounts.filter(a=>a.kind==='debt'&&!a.archived).reduce((n,a)=>n+a.cents,0)||0;
 const maxFuture=Math.max(1,...future.map(f=>f.planned));
 return <main>
  <header className="topbar"><a className="brand" href="/">nosso universo<span>Lucas & Julia <Heart size={13}/></span></a><div className="header-actions"><span className="secure"><ShieldCheck size={16}/> Espaço privado</span><button className="outline" onClick={()=>setSettings(true)}><Wallet size={16}/> Ajustes</button><a className="logout" href="/signout-with-chatgpt?return_to=/" target="_top">Sair</a></div></header>
  <section className="intro"><div><div className="eyebrow">DOIS CORAÇÕES. UM MESMO PLANO.</div><h1>Nosso futuro começa<br/><em>nas escolhas de hoje.</em></h1><p>Cada conta resolvida abre espaço para uma conquista nossa.</p></div><button className={'couple-photo '+(photoAvailable?'has-photo':'')} onClick={()=>fileRef.current?.click()} aria-label="Adicionar ou trocar foto do casal">{photoAvailable?<img src={photo} alt="Lucas e Julia" onError={()=>setPhotoAvailable(false)}/>:<><Heart size={35} strokeWidth={1}/><span>O nosso lugar favorito</span></>}<span className="photo-caption"><Camera size={14}/> Nossa foto</span></button><input ref={fileRef} type="file" accept="image/png,image/jpeg" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void uploadPhoto(f);e.target.value=''}}/></section>
  <div className="toolbar"><div className="month-picker"><button aria-label="Mês anterior" onClick={()=>setMonth(addMonth(month,-1))}><ArrowLeft size={18}/></button><div><span>Nosso planejamento</span><input aria-label="Mês de referência" type="month" value={month} min="2020-01" max="2099-12" onChange={e=>e.target.value&&setMonth(e.target.value)}/></div><button aria-label="Próximo mês" onClick={()=>setMonth(addMonth(month,1))}><ArrowRight size={18}/></button></div><div className="toolbar-right"><Choice value={person} onChange={setPerson} label="Filtrar pessoa" items={['Todos','Lucas','Julia'].map(x=>({value:x,label:x==='Todos'?'Nós dois':x}))}/><button className="primary" disabled={!state||busy} onClick={()=>setEdit({id:crypto.randomUUID(),person:'Lucas',name:'',kind:'installment',cents:0,day:null,start:month,end:month,quantity:1,enabled:true,archived:false})}><Plus size={17}/> Nova conta</button></div></div>
  {error&&<div className="alert error" role="alert">{error}<button onClick={()=>void load()}><RefreshCw size={15}/> {conflict?'Atualizar dados':'Tentar novamente'}</button></div>}
  {notice&&<div className="notice" role="status"><Check size={17}/>{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice('')}>×</button></div>}
  {!state||!all||!t?<div className="loading"><Heart size={25}/><p>{error?'Seu painel está protegido. Entre novamente se necessário.':'Preparando o nosso universo…'}</p><a href="/signin-with-chatgpt?return_to=/" target="_top">Entrar com ChatGPT</a></div>:<>
  <section className="metrics"><article className="metric"><span>Renda mensal <Wallet size={17}/></span><strong>{money(t.income)}</strong><small>{person==='Todos'?'Lucas + Julia':person}</small></article><article className="metric accent"><span>Falta pagar <CalendarDays size={17}/></span><strong>{money(t.pending)}</strong><small>{pending.length} {pending.length===1?'conta pendente':'contas pendentes'} neste mês</small></article><article className="metric"><span>Já pagamos <Check size={17}/></span><strong className="green">{money(t.paid)}</strong><small>{paid.length} {paid.length===1?'conta concluída':'contas concluídas'}</small></article><article className="metric"><span>Saldo após todas as contas <TrendingUp size={17}/></span><strong className={t.balance<0?'red':''}>{money(t.balance)}</strong><small>Renda menos o previsto no mês</small></article></section>
  <div className="budget-note"><span className="mini-heart">♡</span><p>{t.balance<0?<>Precisamos ajustar <b>{money(-t.balance)}</b> para equilibrar {monthName(month)}. Um passo de cada vez, no mesmo time.</>:<>Temos <b>{money(t.balance)}</b> de margem no planejamento de {monthName(month)}. Vamos dar um destino a esse dinheiro?</>}<small>Previsto: {money(t.planned)}. Pagar reduz “Falta pagar”; o saldo previsto não aumenta porque o dinheiro já foi usado.</small></p></div>
  <Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="main-tabs"><TabsTrigger value="month">Contas do mês</TabsTrigger><TabsTrigger value="future">Próximos meses</TabsTrigger><TabsTrigger value="registry">Todas as contas</TabsTrigger><TabsTrigger value="dreams">Nossos sonhos</TabsTrigger></TabsList>
  <TabsContent value="month"><div className="section-head"><div><h2>{filter==='pending'?'Uma conta a menos. Um respiro a mais.':'O que já resolvemos juntos.'}</h2><p>{filter==='pending'?'Marque como paga e ela sai desta lista.':'O histórico fica guardado. Você pode desfazer um pagamento.'}</p></div><Choice value={filter} onChange={setFilter} label="Situação das contas" items={[{value:'pending',label:`A pagar (${pending.length})`},{value:'paid',label:`Pagas (${paid.length})`}]}/></div>
  {month<state.baseline&&<div className="alert">Período anterior ao início do controle. Não sabemos quais destas parcelas já foram pagas. Revise antes de considerar atraso.</div>}
  <div className="account-list">{shown.length===0?<div className="empty"><Check size={30}/><h3>{filter==='pending'?'Tudo em dia neste mês.':'Nenhum pagamento registrado ainda.'}</h3><p>{filter==='pending'?'As contas concluídas continuam disponíveis em “Pagas”.':'Quando vocês concluírem uma conta, ela aparecerá aqui.'}</p></div>:shown.map(r=>{const a=r.account;const late=!r.payment&&r.due&&r.due<todayBR()&&month>=state.baseline;return <article className="account-row" key={r.key}><div className={'avatar '+a.person.toLowerCase()}>{a.person[0]}</div><div className="account-name"><strong>{a.name}</strong><span>{a.person} · {labels[a.kind]}{a.kind==='installment'?` · ${Number(month.slice(0,4))*12+Number(month.slice(5))-(Number(a.start.slice(0,4))*12+Number(a.start.slice(5)))+1}/${a.quantity}`:''}</span></div><div className="due"><span className={late?'red':''}>{r.due?new Date(r.due+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}):'Dia a definir'}</span><small>{r.payment?'Concluída':late?'Vencida':month<state.baseline?'Não confirmado':'Vencimento'}</small></div><strong className="row-value">{money(r.payment?.cents??a.cents)}</strong><button className={r.payment?'outline':'pay-button'} disabled={busy} onClick={()=>pay(a,month,!!r.payment)} aria-label={(r.payment?'Desfazer pagamento de ':'Marcar como paga: ')+a.name+' de '+a.person}>{r.payment?<RotateCcw size={16}/>:<Check size={17}/>}<span>{r.payment?'Desfazer':'Concluir'}</span></button></article>})}</div>
  {state.accounts.some(a=>a.kind==='optional'&&scheduled(a,month))&&<div className="optional-box"><h3>Usamos esses cartões neste mês?</h3><p>Limites opcionais ficam fora da conta. Inclua somente se houver gasto; edite o valor no cadastro se necessário.</p>{state.accounts.filter(a=>a.kind==='optional'&&scheduled(a,month)).map(a=>{const included=state.optionalMonths.includes(keyFor(a,month));return <div className="optional-row" key={a.id}><span>{a.name} · {a.person}</span><b>{money(a.cents)}</b><button className="outline" disabled={busy||!!state.payments[keyFor(a,month)]} onClick={()=>void mutate(s=>{s.optionalMonths=included?s.optionalMonths.filter(k=>k!==keyFor(a,month)):[...s.optionalMonths,keyFor(a,month)]},included?'Gasto opcional retirado do mês.':'Gasto incluído no mês.')}>{included?'Retirar do mês':'Incluir no mês'}</button></div>})}</div>}
  <div className="couple-summary">{(['Lucas','Julia'] as const).map(p=>{const x=totals(state,month,p);return <div key={p}><h3>{p} <Heart size={15}/></h3><div><span>A pagar</span><b>{money(x.pending)}</b></div><div><span>Concluído</span><b className="green">{money(x.paid)}</b></div><Progress value={x.planned?x.paid/x.planned*100:0}/><small>{x.rows.filter(r=>r.payment).length} de {x.rows.length} contas concluídas</small></div>})}</div>
  </TabsContent>
  <TabsContent value="future"><div className="section-head"><div><h2>Mais leve a cada capítulo.</h2><p>Projeção de 12 meses a partir de {monthName(month)}. Clique em um mês para ver suas contas.</p></div></div><div className="forecast">{future.map(f=><button className="forecast-month" key={f.month} onClick={()=>{setMonth(f.month);setTab('month');setFilter('pending')}}><span>{monthName(f.month)}</span><div className="bar-track"><div style={{width:(f.planned/maxFuture*100)+'%'}}/></div><strong>{money(f.pending)}<small>a pagar · {money(f.paid)} pago</small></strong><ArrowRight size={16}/></button>)}</div><p className="footnote">Contas fixas repetem mensalmente. Parcelas encerram no término cadastrado. Renda constante na projeção; opcionais só entram nos meses selecionados. Não inclui dívidas sem acordo.</p></TabsContent>
  <TabsContent value="registry"><div className="section-head"><div><h2>Sem perder nenhum detalhe.</h2><p>Quantidade = total original. Início calculado pela data final. Os pagamentos passados não foram presumidos.</p></div><button className="outline" onClick={download}><Download size={16}/> Backup</button></div><div className="table-panel"><Table><TableHeader><TableRow><TableHead>Conta</TableHead><TableHead>Pessoa</TableHead><TableHead>Valor</TableHead><TableHead>Período</TableHead><TableHead>Situação</TableHead><TableHead>Ações</TableHead></TableRow></TableHeader><TableBody>{state.accounts.filter(a=>person==='Todos'||a.person===person).map(a=><TableRow key={a.id}><TableCell><strong>{a.name}</strong><small>{labels[a.kind]}{a.kind==='installment'?` · ${a.quantity} parcelas`:''}</small></TableCell><TableCell>{a.person}</TableCell><TableCell>{money(a.cents)}</TableCell><TableCell>{a.kind==='debt'?'Sem acordo':<>{monthName(a.start)}<small>{a.end?'até '+monthName(a.end):'recorrente'}</small></>}</TableCell><TableCell>{a.archived?<span className="badge">Arquivada</span>:a.kind==='debt'?<span className="badge debt">A negociar</span>:a.start<state.baseline?<span className="badge">Revisar histórico</span>:<span className="badge">Ativa</span>}</TableCell><TableCell><div className="row-actions"><button aria-label={'Editar '+a.name+' de '+a.person} className="icon-button" onClick={()=>setEdit(a)}><Pencil size={16}/></button><button aria-label={a.archived?'Reativar conta':'Arquivar conta'} className="icon-button" disabled={busy} onClick={()=>a.archived?void mutate(s=>{s.accounts.find(x=>x.id===a.id)!.archived=false},'Conta reativada.'):setArchive(a)}>{a.archived?<RotateCcw size={16}/>:<Archive size={16}/>}</button></div></TableCell></TableRow>)}</TableBody></Table></div><div className="debt-total"><div><span>Dívidas sem acordo</span><h3>{money(totalDebt)}</h3></div><p>Separadas do orçamento mensal. Ao negociar, arquive a dívida original e cadastre o acordo como parcelas, evitando duplicidade.</p></div><details className="history"><summary>Parcelas anteriores a setembro/2026: conferir pagamentos</summary><p>Estas parcelas pertencem ao total original, mas não há comprovantes de pagamento informados. Elas não entram nos compromissos de setembro em diante. Escolha o mês abaixo para conferir e marcar individualmente.</p>{state.accounts.filter(a=>a.kind==='installment'&&a.start<state.baseline).map(a=>{let months:string[]=[];for(let m=a.start;m<state.baseline&&m<=a.end;m=addMonth(m,1))months.push(m);return <div key={a.id}><b>{a.name} · {a.person}</b><div className="history-months">{months.map(m=><button key={m} className={state.payments[keyFor(a,m)]?'done':''} onClick={()=>{setMonth(m);setTab('month');setFilter(state.payments[keyFor(a,m)]?'paid':'pending')}}>{monthName(m)}{state.payments[keyFor(a,m)]?' ✓':''}</button>)}</div></div>})}</details></TabsContent>
  <TabsContent value="dreams"><div className="section-head"><div><h2>Dinheiro com um porquê.</h2><p>Guardar hoje para viver juntos amanhã.</p></div><button className="outline" onClick={()=>setGoalOpen(true)}><Pencil size={15}/> Editar sonhos</button></div><div className="goals">{state.goals.map(g=><article key={g.id}><Sparkles size={24}/><h3>{g.name}</h3><strong>{money(g.saved)}</strong><p>{g.target?'de '+money(g.target):'Vamos definir um valor para esse sonho?'}</p><Progress value={g.target?Math.min(100,g.saved/g.target*100):0}/><small>{g.target?new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(g.saved/g.target*100)+'% do nosso sonho':'Um plano começa com o primeiro passo.'}</small></article>)}</div><p className="footnote">Atualização manual. Os valores guardados não são descontados automaticamente da renda do mês.</p></TabsContent>
  </Tabs>
  <section className="romance"><div className="eyebrow">EM TODOS OS UNIVERSOS</div><Heart size={22}/><blockquote>“{quotes[quote][0]}”</blockquote><p>Inspirado em {quotes[quote][1]}</p><div className="quote-controls"><button aria-label="Frase anterior" onClick={()=>setQuote((quote+quotes.length-1)%quotes.length)}><ArrowLeft size={17}/></button><button aria-label={paused?'Retomar frases':'Pausar frases'} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button aria-label="Próxima frase" onClick={()=>setQuote((quote+1)%quotes.length)}><ArrowRight size={17}/></button></div><small>Textos autorais inspirados no universo Marvel. Não são falas oficiais.</small></section>
  <footer><span>Feito de planos, coragem e nós dois. ♡</span><span><LockKeyhole size={13}/> Salvo online · atualização a cada 20 s <button onClick={()=>void load()} aria-label="Atualizar agora"><RefreshCw size={14}/></button></span></footer>
  </>}
  <Dialog open={!!edit} onOpenChange={o=>!o&&setEdit(null)}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{state?.accounts.some(a=>a.id===edit?.id)?'Editar conta':'Uma nova conta no plano'}</DialogTitle><DialogDescription>Valores em reais. Deixe o dia em branco se ainda não souber.</DialogDescription></DialogHeader>{edit&&<form key={edit.id} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const kind=edit.kind;const end=kind==='installment'?String(f.get('end')):'';const quantity=kind==='installment'?Number(f.get('quantity')):1;const start=kind==='installment'?addMonth(end,-quantity+1):String(f.get('start'));const account={...edit,name:String(f.get('name')).trim(),cents:parseMoney(String(f.get('value'))),day:f.get('day')?Number(f.get('day')):null,start,end,quantity};if(!account.name||!start)throw Error('Preencha o nome e o período.');const ok=await mutate(s=>{const i=s.accounts.findIndex(a=>a.id===account.id);if(i<0)s.accounts.push(account);else s.accounts[i]=account},'Conta salva. O planejamento foi atualizado.');if(ok)setEdit(null)}catch(err){setError((err as Error).message)}}}><label>Nome da conta<input name="name" required maxLength={100} defaultValue={edit.name}/></label><div className="form-grid"><label>Responsável<Choice label="Responsável" value={edit.person} onChange={v=>setEdit({...edit,person:v as 'Lucas'|'Julia'})} items={['Lucas','Julia'].map(v=>({value:v,label:v}))}/></label><label>Tipo<Choice label="Tipo da conta" value={edit.kind} onChange={v=>setEdit({...edit,kind:v as Account['kind']})} items={Object.entries(labels).map(([value,label])=>({value,label}))}/></label></div><div className="form-grid"><CurrencyInput name="value" label={edit.kind==='debt'?'Valor total':'Valor por mês / parcela'} value={edit.cents}/><label>Dia de vencimento<input name="day" type="number" min="1" max="31" defaultValue={edit.day??''} placeholder="Não informado"/></label></div>{edit.kind==='installment'?<div className="form-grid"><label>Total de parcelas<input name="quantity" type="number" min="1" max="600" required defaultValue={edit.quantity}/></label><label>Mês da última parcela<input name="end" type="month" min="2020-01" max="2099-12" required defaultValue={edit.end||month}/></label></div>:<label>Primeiro mês<input name="start" type="month" min="2020-01" max="2099-12" required defaultValue={edit.start}/></label>}<p className="footnote">O início das parcelas é calculado de trás para frente. Alterações afetam as ocorrências pendentes; valores já pagos ficam preservados.</p>{error&&<p role="alert" className="red">{error}</p>}<button className="primary" disabled={busy} type="submit">{busy?'Salvando…':'Salvar conta'}</button></form>}</DialogContent></Dialog>
  <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>O nosso espaço</DialogTitle><DialogDescription>Renda mensal, segurança e cópia dos dados.</DialogDescription></DialogHeader>{state&&<><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const Lucas=parseMoney(String(f.get('Lucas'))),Julia=parseMoney(String(f.get('Julia')));if(await mutate(s=>{s.incomes={Lucas,Julia}},'Rendas atualizadas.'))setSettings(false)}catch(e){setError((e as Error).message)}}}><div className="form-grid"><CurrencyInput name="Lucas" label="Renda de Lucas" value={state.incomes.Lucas}/><CurrencyInput name="Julia" label="Renda de Julia" value={state.incomes.Julia}/></div><p className="footnote">Rendas mantidas da versão anterior. Esta alteração atualiza todos os cenários; não é um histórico de salários.</p><button className="primary" disabled={busy}>Salvar rendas</button></form><div className="access-box"><ShieldCheck size={20}/><div><b>Acesso por convite</b><p>O link exige login e permissão. O e-mail da Julia ainda precisa ser informado ao proprietário para liberar o acesso. Não compartilhem senhas.</p></div></div><div className="settings-buttons"><button className="outline" onClick={download}><Download size={16}/> Baixar backup</button><button className="outline" onClick={()=>restRef.current?.click()}>Restaurar backup</button><button className="outline" onClick={()=>fileRef.current?.click()}><Camera size={16}/> Trocar foto</button>{photoAvailable&&<button className="outline" disabled={busy} onClick={async()=>{const r=await fetch('/api/photo',{method:'DELETE'});if(r.ok){setPhotoAvailable(false);setNotice('Foto removida.')}else setError('Não foi possível remover a foto.')}}>Remover foto</button>}</div><small>O backup contém dados financeiros e não inclui a foto. Guarde em um lugar privado.</small>{error&&<p className="red" role="alert">{error}</p>}</>}</DialogContent></Dialog>
  <input ref={restRef} type="file" accept="application/json" hidden onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw Error('Backup muito grande.');setRestore(JSON.parse(await file.text()))}catch{setError('Não foi possível abrir esse backup.')}e.target.value=''}}/>
  <Dialog open={goalOpen} onOpenChange={setGoalOpen}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>Os sonhos que nos movem</DialogTitle><DialogDescription>Atualize as metas e o valor já guardado.</DialogDescription></DialogHeader>{state&&<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const goals=state.goals.map(g=>({...g,name:String(f.get('name-'+g.id)),target:parseMoney(String(f.get('target-'+g.id))),saved:parseMoney(String(f.get('saved-'+g.id)))}));if(await mutate(s=>{s.goals=goals},'Nossos sonhos foram atualizados.'))setGoalOpen(false)}catch(err){setError((err as Error).message)}}}>{state.goals.map(g=><fieldset key={g.id}><label>Nosso sonho<input name={'name-'+g.id} defaultValue={g.name} required/></label><div className="form-grid"><CurrencyInput name={'target-'+g.id} label="Meta" value={g.target}/><CurrencyInput name={'saved-'+g.id} label="Já guardamos" value={g.saved}/></div></fieldset>)}{error&&<p className="red">{error}</p>}<button className="primary" disabled={busy}>Salvar sonhos</button></form>}</DialogContent></Dialog>
  <AlertDialog open={!!archive} onOpenChange={o=>!o&&setArchive(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Arquivar {archive?.name}?</AlertDialogTitle><AlertDialogDescription>Ela sai das pendências e projeções. Os pagamentos já registrados permanecem no histórico e nos totais pagos. Para apenas concluir uma parcela, use “Concluir”.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>{if(archive)void mutate(s=>{s.accounts.find(a=>a.id===archive.id)!.archived=true},'Conta arquivada. Você pode reativá-la no cadastro.');setArchive(null)}}>Arquivar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <AlertDialog open={!!restore} onOpenChange={o=>!o&&setRestore(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Substituir pelo backup?</AlertDialogTitle><AlertDialogDescription>Isso substitui contas, rendas, metas e pagamentos compartilhados. Baixe uma cópia atual antes de continuar.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>{if(restore)void save(restore,'Backup restaurado.');setRestore(null)}}>Restaurar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
